// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAApo3NFPX0UcfxE1_Fa4KnF5KsX0fZ-vU',
    appId: '1:89819429848:web:1f6c85a18398e439fe10ad',
    messagingSenderId: '89819429848',
    projectId: 'proyecto-monito',
    authDomain: 'proyecto-monito.firebaseapp.com',
    databaseURL: 'https://proyecto-monito-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-monito.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj2wY8hE-7mZvE537Hw_e4HztjmctjCWI',
    appId: '1:89819429848:android:f8cd686d19783b37fe10ad',
    messagingSenderId: '89819429848',
    projectId: 'proyecto-monito',
    databaseURL: 'https://proyecto-monito-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-monito.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo1ftC7BtfR_8K_vj_JL7BJIshDj8Uiv4',
    appId: '1:89819429848:ios:dd0e44d5757133a6fe10ad',
    messagingSenderId: '89819429848',
    projectId: 'proyecto-monito',
    databaseURL: 'https://proyecto-monito-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-monito.appspot.com',
    iosBundleId: 'com.example.proyectoMonito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo1ftC7BtfR_8K_vj_JL7BJIshDj8Uiv4',
    appId: '1:89819429848:ios:d004d4975e7476cbfe10ad',
    messagingSenderId: '89819429848',
    projectId: 'proyecto-monito',
    databaseURL: 'https://proyecto-monito-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-monito.appspot.com',
    iosBundleId: 'com.example.proyectoMonito.RunnerTests',
  );
}
